M48
; DRILL file KiCad 10.0.1 date 2026-07-16T18:28:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-16T18:28:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X133.035Y-79.03
X133.035Y-84.81
T2
X110.85Y-99.515
X110.85Y-105.515
X116.773Y-98.851
X122.773Y-98.851
M30
